name: Build, Test and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud analysis
        run: |
          dotnet sonarscanner begin \
            /k:"wesleyazevedobezerra_CadastroApi" \
            /o:"wesleyazevedobezerra" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="Coverage/coverage.xml"

      - name: Build
        run: dotnet build --no-incremental

      - name: Test with coverage
        run: |
          dotnet test todo_dotnet_core9.Applications.Tests \
            /p:CollectCoverage=true \
            /p:CoverletOutput=Coverage/coverage.xml \
            /p:CoverletOutputFormat=opencover

      - name: List coverage files
        run: |
          ls -la Coverage
          head -30 Coverage/coverage.xml

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
