name: Build, Test and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner tool
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Begin SonarCloud analysis
        run: |
          dotnet sonarscanner begin \
            /k:"wesleyazevedobezerra_CadastroApi" \
            /o:"wesleyazevedobezerra" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="Coverage/coverage.opencover.xml"

      - name: Build solution
        run: dotnet build --no-incremental

      - name: Run tests and collect coverage
        run: |
          mkdir -p Coverage
          dotnet test todo_dotnet_core9.Applications.Tests \
            /p:CollectCoverage=true \
            /p:CoverletOutput=./Coverage/coverage.opencover.xml \
            /p:CoverletOutputFormat=opencover

      - name: List coverage file
        run: ls -la Coverage && head -40 Coverage/coverage.opencover.xml

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
